apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: devops
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: 171040096730.dkr.ecr.us-east-1.amazonaws.com/devops
      ports:
      - name: my-port
        containerPort: 8080
